language: ruby
rvm:
  - 2.0.0
  - 2.1.1
  - 2.1.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.1.2
script:
  - cp .env.sample .env
  - bundle exec rake db:create db:migrate DATABASE_URL=postgres://localhost/citygram_test
  - bundle exec rake
notifications:
  webhooks: http://project-monitor.codeforamerica.org/projects/77db7e4d-a05a-4ee8-b7ab-3bd29c6dd1b0/status
